#ifndef VLCPLAYWINDOW_GLOBAL_H
#define VLCPLAYWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VLCPLAYWINDOW_LIBRARY)
#  define VLCPLAYWINDOWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VLCPLAYWINDOWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VLCPLAYWINDOW_GLOBAL_H
